    defb "?",0
    defb "RND",0
    defb "INKEY$",0
    defb "PI",0
    defb "FN",0
    defb "POINT",0
    defb "SCREEN$",0
    defb "ATTR",0
    defb "AT",0
    defb "TAB",0
    defb "VAL$",0
    defb "LEN",0
    defb "SIN",0
    defb "COS",0
    defb "TAN",0
    defb "ASN",0
    defb "ACS",0
    defb "ATN",0
    defb "LN",0
    defb "EXP",0
    defb "INT",0
    defb "SQR",0
    defb "SGN",0
    defb "ABS",0
    defb "PEEK",0
    defb "IN",0
    defb "USR",0
    defb "STR$",0
    defb "CHR$",0
    defb "NOT",0
    defb "BIN",0
    defb "OR",0
    defb "AND",0
    defb "<=",0
    defb ">=",0
    defb "<>",0
    defb "LINE",0
    defb "THEN",0
    defb "TO",0
    defb "STEP",0
    defb "DEF FN",0
    defb "CAT",0
    defb "FORMAT",0
    defb "MOVE",0
    defb "ERASE",0
    defb "OPEN #",0
    defb "CLOSE #",0
    defb "MERGE",0
    defb "VERIFY",0
    defb "BEEP",0
    defb "CIRCLE",0
    defb "INK",0
    defb "PAPER",0
    defb "FLASH",0
    defb "BRIGHT",0
    defb "INVERSE",0
    defb "OVER",0
    defb "OUT",0
    defb "LPRINT",0
    defb "LLIST",0
    defb "STOP",0
    defb "READ",0
    defb "DATA",0
    defb "RESTORE",0
    defb "NEW",0
    defb "BORDER",0
    defb "CONTINUE",0
    defb "DIM",0
    defb "REM",0
    defb "FOR",0
    defb "GO TO",0
    defb "GO SUB",0
    defb "INPUT",0
    defb "LOAD",0
    defb "LIST",0
    defb "PAUSE",0
    defb "NEXT",0
    defb "POKE",0
    defb "PRINT",0
    defb "PLOT",0
    defb "RUN",0
    defb "SAVE",0
    defb "RANDOMIZE",0
    defb "IF",0
    defb "CLS",0
    defb "DRAW",0
    defb "CLEAR",0
    defb "RETURN",0
    defb "COPY",0

    defb "SPECTRUM",0
    defb "PLAY",0
